### ISSUE TITLE
Only 1 slide is working

### ISSUE THREAD

**Issue by bjornbon** [ualex73/slide#17]
I have 4 slides. Below the relevant part of my yaml file

```
cover:
  - platform: slide
    host: 192.168.1.19
    password: 123456781
    api_version: 2

cover:
  - platform: slide
    host: 192.168.1.21
    password: 123456782
    api_version: 2

cover:
  - platform: slide
    host: 192.168.1.17
    password: 123456783
    api_version: 2

cover:
  - platform: slide
    host: 192.168.2.18
    password: 123456784
    api_version: 2

```

Looks like only the last slide  (192.168.2.18) becomes visible and is working.
If I change the order, again the last mentioned slide is visible and working. The previously visible one becomes fully inactive.

Is there a way to fix this?
